In [1]:
#import keras
from PIL import Image
from keras.layers import Input, Lambda, Dense, Flatten
from keras.models import Model
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

Using TensorFlow backend.


In [2]:
from keras.preprocessing import image
model = load_model('model_vgg16.h5')


In [3]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [ ]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Prajakta'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

[[1.0000000e+00 0.0000000e+00 2.7371756e-32]]
[[1.000000e+00 0.000000e+00 8.382303e-28]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.00000000e+00 0.00000000e+00 1.16133115e-30]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 4.3208792e-38]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 1.5929407e-34]]
[[1.0000000e+00 0.0000000e+00 1.5885594e-34]]
[[1.0000000e+00 0.0000000e+00 1.0338216e-19]]
[[1.0000000e+00 0.0000000e+00 4.4898152e-31]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 1.0305402e-37]]
[[1.0000000e+00 0.0000000e+00 1.0318301e-30]]
[[1.0000000e+00 0.0000000e+00 1.7390107e-26]]
[[1.000000e+00 0.000000e+00 2.882887e-30]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 6.142463e-26]]
[[1.0000000e+00 0.0000000e+00 2.1590393e-33]]
[[1.0000000e+00 0.0000000e+00 2.8503258e-35]]
[[1.0000000e+00 0.0000000e+00 3.9511454e-28]]
[[1.000000e+00 0.000000e+00 1.960752e-31]]
[[1.0000000e+00 1.1756696e-24 9.5510990e-16]]